## Market Capsize changes
The Korea stock exchange(KRX) announces the cap size changes once a year. Cap sizes are categorised by three big titles, large, mid, and small caps. The character of Korean is 대형주, 중형주, and 소형주, respectively. For making dummy variables, I am going to assign numbers instead of using Korean such as 대형주.
The excel spread sheets are downloaded from the KRX website. http://marketdata.krx.co.kr
I add one sample excel sheet for running codes.

In [1]:
import pandas as pd
import numpy as np

In this sample excel sheet, the code name of stock('종목코드') has twelve characteristics of string values. There is no problem in this case. But normally the excel files from the KRX are not well organised, and it has some problems with reading excel file. For example, sometimes the stock code is shorten and 'read_excel' method reads it as integers. So, I added 'dtype=str', and skiprows are depending on the excel sheets.

In [2]:
cap = pd.read_excel('C:/Users/Park/Documents/BEcon/Thesis/Market cap change dates/MarketCap_20160311.xlsx',skiprows=2, dtype=str)
cap.head()

  순위          종목코드    종목명  변경전  변경후  비고
0  1  KR7005930003   삼성전자  대형주  대형주  기존
1  2  KR7015760002   한국전력  대형주  대형주  기존
2  3  KR7005380001    현대차  대형주  대형주  기존
3  4  KR7028260008   삼성물산  미분류  대형주  변경
4  5  KR7012330007  현대모비스  대형주  대형주  기존

Choosing columns what we need.

In [3]:
cap_df = cap.loc[:,['종목코드','변경후']]
cap_df.head()

           종목코드  변경후
0  KR7005930003  대형주
1  KR7015760002  대형주
2  KR7005380001  대형주
3  KR7028260008  대형주
4  KR7012330007  대형주

Running if to construct the dummy variables.

In [4]:
cap_df['Capsize'] = 0
for i in np.arange(len(cap_df)):
    print(cap_df.iloc[i,1])
    if cap_df.iloc[i,1] == '대형주' :
        cap_df.iloc[i,2] = 1
    if cap_df.iloc[i,1] == '중형주' :
        cap_df.iloc[i,2] = 2
    if cap_df.iloc[i,1] == '소형주' :
        cap_df.iloc[i,2] = 3

대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
대형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
중형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주
소형주

In [5]:
cap_df.head()

           종목코드  변경후  Capsize
0  KR7005930003  대형주        1
1  KR7015760002  대형주        1
2  KR7005380001  대형주        1
3  KR7028260008  대형주        1
4  KR7012330007  대형주        1

Because of using the official stock code on the excel sheet, we are going to slice the code to make simplified code. The simplified code is going to be used as a 'name' of each individual stocks.

In [6]:
cap_df['Code'] = cap_df['종목코드'].str.slice(3,9)
cap_df['Code'] = 'A' + cap_df['Code']
cap_df.head()

           종목코드  변경후  Capsize     Code
0  KR7005930003  대형주        1  A005930
1  KR7015760002  대형주        1  A015760
2  KR7005380001  대형주        1  A005380
3  KR7028260008  대형주        1  A028260
4  KR7012330007  대형주        1  A012330

Some excel file contains simplified stock code itself, and other cases the excel file contains different column name. Watch out the column name and contents, and use other code depend on cases.
Two lines below can be used.

In [172]:
cap_df['Code'] = cap_df['종목코드']

In [110]:
cap_df['Code'] = cap_df['단축코드']

Choosing the columns what we need.

In [7]:
cap_save = cap_df.loc[:,['Capsize','Code']]
cap_save.head()

   Capsize     Code
0        1  A005930
1        1  A015760
2        1  A005380
3        1  A028260
4        1  A012330

Save it to excel file, we are going to use the implementation date in the market not announced date. To keep in informed, I am making the file name using the effective date of categories. The cap size categories are valid from 20160311 to 20170310. The date is announced on the document file on the KRX website.

In [8]:
cap_save.to_csv('C:/Users/Park/Documents/BEcon/Thesis/Market cap change dates/MarketCap_20160311_20170310.csv')

## KOSPI 200 Changes
The other structural change is getting in or out of the list of constitution stock of the benchmark index.

In [9]:
k200 = pd.read_excel('C:/Users/Park/Documents/BEcon/Thesis/Market cap change dates/temp.xlsx', dtype=str)
k200.head()

           종목코드    종목명
0  KR7000030007   우리은행
1  KR7000050005     경방
2  KR7000070003  삼양홀딩스
3  KR7000080002  하이트진로
4  KR7000100008   유한양행

In [10]:
k200['Code'] = 'A'+k200['종목코드'].str.slice(3,9)
k200.head()

           종목코드    종목명     Code
0  KR7000030007   우리은행  A000030
1  KR7000050005     경방  A000050
2  KR7000070003  삼양홀딩스  A000070
3  KR7000080002  하이트진로  A000080
4  KR7000100008   유한양행  A000100

In [11]:
k200.to_csv('C:/Users/Park/Documents/BEcon/Thesis/Market cap change dates/KOSPI200_20170609.csv')